### ISSUE TITLE
Rails install

### ISSUE THREAD

**Issue by geraldhiller** [nagoshiashumari/Rpg-Awesome#32]
How would I install this in a rails app? Thanks a lot for your help!

**Comment by tritium21** [comment]
You would serve the font as a static file, and include it in your CSS.  There is nothing rails specific about it.  In fact, since you shouldn't be serving static files through rails at all (you should be using your front end web server to serve both the font and CSS), you *shouldn't* do anything to a rails app to use a font.

**Comment by geraldhiller** [comment]
Which file would I serve?

**Comment by LiamKenneth** [comment]
You need to add the rpg-awesome.css to your html page and make sure the file path for the fonts point to the correct place.

The paths for the fonts are at the top of the css file so [you can't miss them](https://github.com/nagoshiashumari/Rpg-Awesome/blob/master/css/rpg-awesome.css#L11).

Add this between your head tags (make sure file path is correct):
`    <link rel="stylesheet" href="css/rpg-awesome.css" />`

You use the icons like this:
`<i class="ra ra-aware"></i>`

Here's the [full list of icons](http://nagoshiashumari.github.io/Rpg-Awesome/)  keep the ra class and just change the ra-aware to the one you want.

Also there is a [demo file ](https://github.com/nagoshiashumari/Rpg-Awesome/blob/master/demo/index.html )you can checkout that should help.

**Comment by geraldhiller** [comment]
Thanks a lot!
